steps:
  - label: ":pipeline: Launch tests"
    command: buildkite-agent pipeline upload .buildkite/runtests.yml
    agents:
      queue: "juliaecosystem"
      sandbox_capable: true

  - label: ":pipeline: Launch Failing Jobs"
    command: buildkite-agent pipeline upload .buildkite/fail_jobs.yml
    agents:
      queue: "juliaecosystem"
      sandbox_capable: true
