self_test_setup: &self_test_setup
  post-checkout: |
    mkdir -p .buildkite/plugins/jack
    cp -Ra hooks lib plugin.yml README.md .buildkite/plugins/jack/

steps:
  - label: ":bucket: Test jack"
    agents:
      arch: "x86_64"
      os: "linux"
      queue: "juliaecosystem"
    plugins:
      # In order to properly use the current repository as a plugin within a pipeline,
      # we have to first install it into the "vendored plugin" location.
      - staticfloat/metahook#sf/windows_backslashes:
          <<: *self_test_setup
      - JuliaCI/julia#v1:
          version: 1
      - staticfloat/sandbox#v1:
          rootfs_url: "https://github.com/staticfloat/Sandbox.jl/releases/download/debian-minimal-927c9e7f/debian_minimal.tar.gz"
          rootfs_treehash: "5b44fab874ec426cad9b80b7dffd2b3f927c9e7f"
          verbose: true
          workspaces:
            #! Include `/cache` so that `julia` install can properly cache its Julia downloads
            - "/cache:/cache"
            #! Include `~/.ssh` so that we get the pre-filled `known_hosts` file
            - "$${HOME}/.ssh:/root/.ssh"

      - "./.buildkite/plugins/jack":
          install:
            # Install a precise version of `make_jll`
            # - "make_jll#v1.0.0+0"
            # Just grab the latest version of FFMPEG_jll that we can find
            - "FFMPEG_jll"

    commands: |
      ffmpeg -version
